-- Populate UI resources from Angular routes (WINDOW level)
INSERT INTO ressource_ui (code_resource, type_resource, libelle, est_menu, actif, created_by, rowscn)
VALUES
('/security/utilisateur', 'WINDOW', 'Utilisateurs', 'Y', 'Y', 'system', 1),
('/security/role-groupe', 'WINDOW', 'Groupes de Rôles', 'Y', 'Y', 'system', 1),
('/security/app-role', 'WINDOW', 'Rôles', 'Y', 'Y', 'system', 1),
('/settings/user-profile', 'WINDOW', 'Profil Utilisateur', 'Y', 'Y', 'system', 1),
('/hr/production-piece', 'WINDOW', 'Production de pièces', 'Y', 'Y', 'system', 1),
('/hr/type-sanction', 'WINDOW', 'Type Sanction', 'Y', 'Y', 'system', 1),
('/hr/niveau-employe', 'WINDOW', 'Niveau Employe', 'Y', 'Y', 'system', 1),
('/hr/domaine', 'WINDOW', 'Domaine', 'Y', 'Y', 'system', 1),
('/hr/niveau-qualification', 'WINDOW', 'Niveau Qualification', 'Y', 'Y', 'system', 1),
('/hr/famille-metier', 'WINDOW', 'Famille Metier', 'Y', 'Y', 'system', 1),
('/hr/type-employe', 'WINDOW', 'Type Employe', 'Y', 'Y', 'system', 1),
('/hr/type-unite-organisationnelle', 'WINDOW', 'Type Unite Organisationnelle', 'Y', 'Y', 'system', 1),
('/hr/unite-organisationnelle', 'WINDOW', 'Unite Organisationnelle', 'Y', 'Y', 'system', 1),
('/hr/devise', 'WINDOW', 'Monnaie', 'Y', 'Y', 'system', 1),
('/hr/fonction', 'WINDOW', 'Fonction', 'Y', 'Y', 'system', 1),
('/hr/groupe-employe', 'WINDOW', 'Groupe Employe', 'Y', 'Y', 'system', 1),
('/hr/institution-tierse', 'WINDOW', 'Institution Tierse', 'Y', 'Y', 'system', 1),
('/hr/rubrique-prestation', 'WINDOW', 'Rubrique Prestation', 'Y', 'Y', 'system', 1),
('/hr/type-conge', 'WINDOW', 'Type Conge', 'Y', 'Y', 'system', 1),
('/hr/type-revenu', 'WINDOW', 'Type Revenu', 'Y', 'Y', 'system', 1),
('/hr/piece', 'WINDOW', 'Definition Piece', 'Y', 'Y', 'system', 1),
('/hr/poste', 'WINDOW', 'Poste', 'Y', 'Y', 'system', 1),
('/hr/jour-conge', 'WINDOW', 'Jour Conge', 'Y', 'Y', 'system', 1),
('/hr/rubrique-paie', 'WINDOW', 'Rubrique Paie', 'Y', 'Y', 'system', 1),
('/hr/horaire', 'WINDOW', 'Horaire', 'Y', 'Y', 'system', 1),
('/hr/regime-paie', 'WINDOW', 'Regime Paie', 'Y', 'Y', 'system', 1),
('/hr/entreprise', 'WINDOW', 'Parametres Principaux Entreprise', 'Y', 'Y', 'system', 1),
('/hr/reference-payroll', 'WINDOW', 'Reference Payroll', 'Y', 'Y', 'system', 1),
('/hr/plan-assurance', 'WINDOW', 'Plan Assurance', 'Y', 'Y', 'system', 1),
('/hr/definition-deduction', 'WINDOW', 'Definition Deduction', 'Y', 'Y', 'system', 1),
('/hr/interface-loading', 'WINDOW', 'Interface de Chargement', 'Y', 'Y', 'system', 1),
('/hr/interface-extraction', 'WINDOW', 'Interface d''Extraction', 'Y', 'Y', 'system', 1),
('/hr/ref-formule-token', 'WINDOW', 'Reference Tokens Formule', 'Y', 'Y', 'system', 1),
('/hr/formule', 'WINDOW', 'Formules', 'Y', 'Y', 'system', 1),
('/hr/param-generation-code-employe', 'WINDOW', 'Generation Code Employe', 'Y', 'Y', 'system', 1),
('/hr/message-definition', 'WINDOW', 'Definition Messages', 'Y', 'Y', 'system', 1),
('/hr/audit-acces', 'WINDOW', 'Audit Acces', 'Y', 'Y', 'system', 1),
('/hr/processus-parametre', 'WINDOW', 'Parametres Processus', 'Y', 'Y', 'system', 1),
('/hr/alert-config', 'WINDOW', 'Configuration Alerte', 'Y', 'Y', 'system', 1),
('/hr/horaire-special', 'WINDOW', 'Horaire Special', 'Y', 'Y', 'system', 1),
('/hr/preavis-parametre', 'WINDOW', 'Parametres Preavis', 'Y', 'Y', 'system', 1),
('/hr/sanction-employe', 'WINDOW', 'Sanction Employe', 'Y', 'Y', 'system', 1),
('/hr/register-group', 'WINDOW', 'Enregistrer En Lot', 'Y', 'Y', 'system', 1),
('/hr/presence', 'WINDOW', 'Presence', 'Y', 'Y', 'system', 1),
('/hr/pointage-brut', 'WINDOW', 'Pointage Brut', 'Y', 'Y', 'system', 1),
('/hr/presence-employe', 'WINDOW', 'Presence Employe', 'Y', 'Y', 'system', 1),
('/hr/absence-employe', 'WINDOW', 'Absence Employe', 'Y', 'Y', 'system', 1),
('/hr/exclusion-deduction', 'WINDOW', 'Exclusion Deduction', 'Y', 'Y', 'system', 1),
('/hr/absence', 'WINDOW', 'Absence', 'Y', 'Y', 'system', 1),
('/hr/leave', 'WINDOW', 'Conge', 'Y', 'Y', 'system', 1),
('/hr/night-work', 'WINDOW', 'Travail Nocturne', 'Y', 'Y', 'system', 1),
('/hr/employe-dossier', 'WINDOW', 'Dossier Employe', 'Y', 'Y', 'system', 1),
('/hr/mutation-employe', 'WINDOW', 'Mutation Employe', 'Y', 'Y', 'system', 1),
('/hr/supplementaire-employe', 'WINDOW', 'Supplementaire Employe', 'Y', 'Y', 'system', 1),
('/hr/pret-employe', 'WINDOW', 'Pret Employe', 'Y', 'Y', 'system', 1),
('/hr/autre-revenu-employe', 'WINDOW', 'Autre Revenu Employe', 'Y', 'Y', 'system', 1),
('/hr/payroll', 'WINDOW', 'Payroll', 'Y', 'Y', 'system', 1),
('/hr/conge-employe', 'WINDOW', 'Conge Employe', 'Y', 'Y', 'system', 1)
ON CONFLICT (code_resource) DO NOTHING;
